
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/academia?userTimezone=true&serverTimezone=UTC&legacyDate
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.format_sql: true